export const OKTA_URL = process.env.REACT_APP_AUTH_URL!;
export const CLIENT_ID = process.env.REACT_APP_CLIENT_ID!;
export const REDIRECT_URI = process.env.REACT_APP_REDIRECT_URI!;
export const AUTH_SERVER = process.env.REACT_APP_AUTH_SERVER || "default";
export const RESPONSE_TYPE = "token id_token";
export const SCOPE = "openid profile groups email";
export const STATE = "state";
export const NONCE = "nonce";
export const AUDIENCE = "api://default";
